// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjQ6sDnKx6b1SmTNuKNj-P_Wus6BqWAPM',
    appId: '1:116690974908:web:7ffbc32db50a43ec3638b9',
    messagingSenderId: '116690974908',
    projectId: 'alemeno-assignment-8de15',
    authDomain: 'alemeno-assignment-8de15.firebaseapp.com',
    storageBucket: 'alemeno-assignment-8de15.appspot.com',
    measurementId: 'G-7RJ7634NCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPPbG__ANiaJXBIl_jwyhCTqnfEG6bflM',
    appId: '1:116690974908:android:0e17f93cec1426e93638b9',
    messagingSenderId: '116690974908',
    projectId: 'alemeno-assignment-8de15',
    storageBucket: 'alemeno-assignment-8de15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCLa8l3gfdVoRPKaKvfK3NQOZ6w_XTP9g',
    appId: '1:116690974908:ios:fe5a736bcbea78ba3638b9',
    messagingSenderId: '116690974908',
    projectId: 'alemeno-assignment-8de15',
    storageBucket: 'alemeno-assignment-8de15.appspot.com',
    iosBundleId: 'com.rizkiazka.alemenoInternshipAssignmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCLa8l3gfdVoRPKaKvfK3NQOZ6w_XTP9g',
    appId: '1:116690974908:ios:c34268fb8da511133638b9',
    messagingSenderId: '116690974908',
    projectId: 'alemeno-assignment-8de15',
    storageBucket: 'alemeno-assignment-8de15.appspot.com',
    iosBundleId: 'com.rizkiazka.alemenoInternshipAssignmentApp.RunnerTests',
  );
}
